language: cpp

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/miniconda

install:
  - bash ci/travis/install.sh

script:
  - pytest -ra -vv .

before_cache:
  - rm -f $HOME/miniconda/envs/thermofun/conda-meta/history*  # Delete these history files to prevent a new cache upload step.
